### ISSUE TITLE
Opam installation failed with OCaml 4.12.0

### ISSUE THREAD

**Issue by gbdrt** [inria-parkas/sundialsml#10]
Installation failed with OCaml 4.12.0 (see error log below).
With MacOS big Sur (11.2.3), and sundials 3.2.1

```
[ERROR] The installation of sundialsml failed at "make install-findlib".

#=== ERROR while installing sundialsml.3.1.1p0-1 ==============================#
# context     2.0.7 | macos/x86_64 | ocaml-base-compiler.4.12.0 | https://opam.ocaml.org#6904c8dd
# path        ~/.opam/4.12.0/.opam-switch/build/sundialsml.3.1.1p0-1
# command     ~/.opam/opam-init/hooks/sandbox.sh install make install-findlib
# exit-code   2
# env-file    ~/.opam/log/sundialsml-26316-d2c37b.env
# output-file ~/.opam/log/sundialsml-26316-d2c37b.out
### output ###
# [...]
# ocamlopt.opt -bin-annot -I sundials -I nvectors -I lsolvers -I cvode -I cvodes -I ida -I idas -I arkode -I kinsol  -c nvectors/nvector.ml
# ocamlopt.opt -bin-annot -I sundials -I nvectors -I lsolvers -I cvode -I cvodes -I ida -I idas -I arkode -I kinsol  -c nvectors/nvector_serial.ml
# ocamlopt.opt -bin-annot -I sundials -I nvectors -I lsolvers -I cvode -I cvodes -I ida -I idas -I arkode -I kinsol  -c lsolvers/sundials_Matrix.ml
# ocamlopt.opt -bin-annot -I sundials -I nvectors -I lsolvers -I cvode -I cvodes -I ida -I idas -I arkode -I kinsol  -c lsolvers/sundials_LinearSolver_impl.ml
# ocamlopt.opt -bin-annot -I sundials -I nvectors -I lsolvers -I cvode -I cvodes -I ida -I idas -I arkode -I kinsol  -c lsolvers/sundials_LinearSolver.ml
# File "lsolvers/sundials_LinearSolver.ml", line 1:
# Error: The files lsolvers/sundials_LinearSolver_impl.cmi
#        and lsolvers/sundials_LinearSolver.cmi make inconsistent assumptions
#        over interface Sundials_LinearSolver_impl
# make[1]: *** [variables.mk:16: lsolvers/sundials_LinearSolver.cmx] Error 2
# make[1]: Leaving directory '/Users/gbaudart/.opam/4.12.0/.opam-switch/build/sundialsml.3.1.1p0-1/src'
# make: *** [Makefile:57: install-findlib] Error 2
```

**Comment by tbrk** [comment]
It's strange. If you do `rm src/lsolvers/sundials_LinearSolver_impl.cmo; make`, the build makes progress before blocking on a similar problem that can be solved in the same way, and so on until an expected problem regarding the redefinition of `Val_none` and `Some_val` (which I know how to fix). Strange...

**Comment by tbrk** [comment]
Wait for `4.12.1` or spend a few hours digging?...

**Comment by tbrk** [comment]
Ok for the duplicate definitions: 3517b131b49ceb4dacc2deb6adc7c7f917c95374.
Otherwise the fix `rm` "fix" does not work, it becomes an endless loop. I'll have a closer look...

**Comment by tbrk** [comment]
I've found the problem.
```
ocamlc.opt ... -c lsolvers/sundials_LinearSolver_impl.ml
# lsolvers/sundials_LinearSolver_impl.cmi has hash ab3d9560632ec6520886dee7a4d250b6
ocamlopt.opt ... -c lsolvers/sundials_LinearSolver_impl.ml
# lsolvers/sundials_LinearSolver_impl.cmi has hash 7bbd17e65f97070867878adb2bb47e3a
```
In fact, the difference is that `ocamlopt.opt` is given the `-no-alias-deps` flag but `ocamlc.opt` is not.

On scanning the list of changes for OCaml 4.12.0, it turns out that the compiler devs already knew about this problem
(https://github.com/ocaml/ocaml/pull/9991#issuecomment-767615833)!

I just have to work out why this option is passed and maybe it can simply also be passed to `ocamlc.opt`.

**Comment by tbrk** [comment]
ocaml/opam-repository#18333
Now I "just" need to finish the work for Sundials 5.x...

**Comment by Octachron** [comment]
Note that this was the motivation for #9 .

**Comment by tbrk** [comment]
Which I somehow missed. As I said on the other thread: thank you for the patch and sorry for missing it. I'll have to find a way to configure github to send me emails when issues are raised against inria-parkas/sundialsml...
