### ISSUE TITLE
opam packaging comments

### ISSUE THREAD

**Issue by gasche** [inria-parkas/sundialsml#2]
Two comments on opam packaging from having a quick look at the new opam packages.

1. It is customary and useful to have an `opam` file at the root of the project sources, from which the opam files submitted to the opam-repository at release time are derived. This source-local package may have a version field indicating the next version, or just `dev`. This enables [package pinning](https://opam.ocaml.org/blog/opam-1-2-pin/): people that would download the sources and tweak them can easily convince opam to let them install this tweaked version of the package in stead of the default one.

2. Rather than having `depexts` field in your package description, it is often useful to separate them in separate `conf-*` packages that encapsulate a bunch of depexts on many different systems. In your case, `sundials` is arguably a package-specific dependency (one could create a `conf-lapack` package but you would be the only user), but there already is a [conf-lapack](http://opam.ocaml.org/packages/conf-lapack/conf-lapack.1/) package and it would be better to depend on it rather than list the same depext dependencies. In particular, the package contains a piece of code to detect the presence of the library at build time and it will fail explicitly if it is absent from the system. On the other hand, `conf-lapack` does not have the `lapack` depext, so you should probably add it there (by sending a pull request to the opam-repository). The advantage is that it shares the work between packages.

**Comment by tbrk** [comment]
Thanks for these pointers and the links (I often get lost when trying to find good information about creating OPAM packages). I will implement both suggestions soon.

We also wanted to add options for installing the Sundials/ML docs. As far as I could understand, the treatment of docs is in a state of flux and it may be better to wait for a few more months. Would you know if that is accurate?

**Comment by gasche** [comment]
I don't know much about the doc, sorry. I would have done [what you have already done](https://github.com/ocaml/opam-repository/blob/master/packages/sundialsml/sundialsml.2.6.2p0/opam#L27-L30) with a `build-doc` target. Did you try building the package with `opam install --build-doc` to see if it works as intended? One thing that I wonder is if `--docdir=%{doc}%` is the right setting -- I would expect opam to give the global documentation repository (`opam config var doc`), and the configure to use instead a package-local subdirectory eg. `--docdir=%{doc}%/sundialsml` as done in [trie](https://github.com/ocaml/opam-repository/blob/master/packages/trie/trie.0.1.1/opam#L13) for example, but maybe your build scripts take care of that somewhere else. This, and having a `doc` field with the documentation over the internet, seems to be the best we can do right now.

**Comment by tbrk** [comment]
OK.

I added an OPAM file for pinning (5bee3135e424f0814417bd3e5198d20cb785f2c9), and fixed the doc directory setting (99412bcbe8e1e9c07a924a92a7755defaf31cfaf; thanks for spotting this).

The conf-lapack issue seems trickier to me. We only need lapack when the underlying Sundials library is built with LAPACK_ENABLE=1, and this depends on the package. It is enabled in Fedora/EPEL, but not in Debian/Ubuntu, Homebrew, or MacPorts. I would need to be able to express something like:
```
depends: [
  "base-bigarray"
  "ocamlfind"
  "conf-lapack" {dist="fedora" | dist="centos"}
]
```
But as far as I could tell from the [opam manual, sec 9](http://opam.ocaml.org/doc/manual/dev-manual.html#sec9), only dependency flags and versions are allowed.

**Comment by gasche** [comment]
Indeed, it seems that this advice was too heavy-handed. Thanks for the explanation: I've been thinking about which kind of packaging policies we could try to enforce around `depext` and `conf-*` packages, and this is a corner case I hadn't really thought of.

(On the other hand, I would expect packagers on distribution that assume LAPACK to also make their `sundials-dev` package depends on their `lapack-dev` package. It seems that this is not the case, which explains why you have to differentiate on your end.)

**Comment by tbrk** [comment]
You're spot on, and I had already forgotten that detail, the need to include `lapack-dev` could be considered an upstream packaging issue: [Red Hat Bugzilla: 1319267](https://bugzilla.redhat.com/show_bug.cgi?id=1319267).

I was happy to learn about `conf-*`, I wondered what those things were.
