### ISSUE TITLE
print functions for the array types?

### ISSUE THREAD

**Issue by nilsbecker** [inria-parkas/sundialsml#3]
as a suggestion: for user convenience would it make sense to define print functions e.g. for Sundials.Realarray.t that can be used with `#install_printer` in the toplevel and with `@a` in format strings?

**Comment by tbrk** [comment]
This is a nice idea. We once had a simple printing function (https://github.com/inria-parkas/sundialsml/commit/6f9d00e2c4b36b40a2676b4900c4a6af719cf4d5#diff-46fb91b6f30dcaa5d6d4c11956cf11df), but it was too ad hoc to keep.

The idea of a formatter function is more convincing. Even though Sundials.RealArray.t is just a synonym for a Bigarray.Array1 of floats, it is central to the Sundials/ML library and we already include several convenience functions.

But what kind of interface should we provide for the choice of separators and the display of floats?
Maybe something like [Format.pp_print_list](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Format.html#VALpp_print_list)? And also a simpler version defaulting to string_of_float and semi-colons as separators?

**Comment by nilsbecker** [comment]
another point of comparison might be `CCFormat.array` in containers, https://github.com/c-cube/ocaml-containers/blob/master/src/core/CCFormat.mli. i would think some optional arguments could be the way to go, with defaults equal to (big)array ? also, one could think of providing a float formatter function of type `Format.formatter -> float -> unit` as an optional argument to let the user control the precision.

there are also some other vector types in the library (i don't have any detailed knowledge at all), so one could also think of making similar printers for the others?

**Comment by tbrk** [comment]
Thanks for the suggestion. Pretty printers added!
