### ISSUE TITLE
sundials 3.1 homebrew

### ISSUE THREAD

**Issue by nilsbecker** [inria-parkas/sundialsml#6]
hi, i tried to install sundialsml on os x. beforehand i installed sundials via homebrew. at various stages, i got error messages:

- `opam depext sundialsml` complains about homebrew/science/sundials but that is deprecated in favor of homebrew/sundials.
- at some point i was able to get opam installation to start. however then no file `sundials_config.h` could be found so that compliation of sundialsml stopped at the configure stage. 

i finally got it to work after downgrading sundials to version 2.7.0_3 using homebrew.

it seems either sundialsml or some installation step on os x is incompatible with sundials 3.1 ?

**Comment by tbrk** [comment]
Hello, I've not yet had a chance to upgrade the Sundials/ML interface to 3.1. I'm hoping to have some time to look into it over the Christmas break. Are you OK using 2.7 for the time being?

**Comment by nilsbecker** [comment]
sure. just inquiring to make sure this is not just an oversight.

**Comment by tbrk** [comment]
If you don't mind @nilsbecker, I will keep this issue open to remind me until the upgrade is done.

**Comment by nilsbecker** [comment]
just ran into this again after updating ocaml to 4.06.1. i had forgotten about the sundials version requirements. 

`opam depext sundialsml.2.7.0p0` did not complain, except for indicating that sundials had moved to the core repository.

**Comment by tbrk** [comment]
Thanks for the extra info. We've made [good progress](https://github.com/inria-parkas/sundialsml/commits/3.1.0-dev) on the upgrade to 3.x (aiming at keeping backward compatibility with the 2.x series). I hope to wrap this up and fix the outstanding issues very soon.

**Comment by tbrk** [comment]
Fixed by the [v3.1.1p0 release](https://github.com/inria-parkas/sundialsml/releases/tag/v3.1.1p0)!
